#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 1
#SBATCH -J Trimming
#SBATCH -t 01:00:00

module load bioinfo-tools
module load TrimGalore/0.4.4

#cat r1 r1 r1 r1.fastq.gz > fastq.gz

#Adapter-trimming and QC-trimming
trim_galore --illumina --paired --fastqc --quality 20 --output_dir /proj/Controls Control1_*
trim_galore --illumina --paired --fastqc --quality 20 --output_dir /proj/Controls Control2_*
trim_galore --illumina --paired --fastqc --quality 20 --output_dir /proj/Controls Control3_*

echo TrimGalore done
