#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 6
#SBATCH -J ReorderSam
#SBATCH -t 12:00:00

module load bioinfo-tools
module load samtools/1.9
module load picard/2.10.3


#make ReorderSam-file

java -jar $PICARD_HOME/picard.jar ReorderSam \
        I=Control01.sam \
        O=Control01_Reordered.bam \
        R=/sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
        CREATE_INDEX=TRUE

java -jar $PICARD_HOME/picard.jar ReorderSam \
        I=Control02.sam \
        O=Control02_Reordered.bam \
        R=/sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
        CREATE_INDEX=TRUE
        
java -jar $PICARD_HOME/picard.jar ReorderSam \
        I=Control03.sam \
        O=Control03_Reordered.bam \
        R=/sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
        CREATE_INDEX=TRUE
        
 echo ReorderSAM done
