#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 6
#SBATCH -J BaseRecalibrator
#SBATCH -t 36:00:00

module load bioinfo-tools
module load GATK/3.8-0


#Base recalibration

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T BaseRecalibrator \
    -I Control01_DupRemoved.bam \
    -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
    -L /proj/AsperBio_nexterarapidcapture_exome_targetedregions_Manifest_v1.2_chr_changed_noM.bed \
    --knownSites /sw/data/uppnex/GATK/2.8/b37/1000G_phase1.snps.high_confidence.b37.vcf \
    -o Control01.BaseRecalibrator.table

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T BaseRecalibrator \
    -I Control02_DupRemoved.bam \
    -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
    -L /proj/AsperBio_nexterarapidcapture_exome_targetedregions_Manifest_v1.2_chr_changed_noM.bed \
    --knownSites /sw/data/uppnex/GATK/2.8/b37/1000G_phase1.snps.high_confidence.b37.vcf \

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T BaseRecalibrator \
    -I Control03_DupRemoved.bam \
    -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
    -L /proj/AsperBio_nexterarapidcapture_exome_targetedregions_Manifest_v1.2_chr_changed_noM.bed \
    --knownSites /sw/data/uppnex/GATK/2.8/b37/1000G_phase1.snps.high_confidence.b37.vcf \
    
 echo BaseRecalibration done  
