#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p node
#SBATCH -n 16
#SBATCH -J CombineGVCFs
#SBATCH -t 80:00:00

module load bioinfo-tools
module load GATK/3.8-0


#Merge gvcf files

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T CombineGVCFs \
      -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
      -L /proj/AsperBio_nexterarapidcapture_exome_targetedregions_Manifest_v1.2_chr_changed_noM.bed \
      --variant Control01.g.vcf \
      --variant Control02.g.vcf \
      --variant Control03.g.vcf \
      --out Control01_Control02_Control03.g.vcf

echo CombineGVCFs done
