#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 16
#SBATCH -J GenotypeGVCFs
#SBATCH -t 48:00:00

module load bioinfo-tools
module load GATK/3.8-0


java -Xmx16g -jar $GATK_HOME/GenomeAnalysisTK.jar -T GenotypeGVCFs \
      -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
      -L /proj/AsperBio_nexterarapidcapture_exome_targetedregions_Manifest_v1.2_chr_changed_noM.bed \
      --variant Control01_Control02_Control03.g.vcf \
      --variant Control04_Control05_Control06.g.vcf \
      --variant Control07_Control08_Control09.g.vcf \
      --variant Control10_Control11_Control12.g.vcf \
      --variant Control13_Control14_Control15_Control16.g.vcf \
      --out Controls_date.vcf


echo GenotypeGVCF done

