#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 1
#SBATCH -J ExtractOnlySNPs
#SBATCH -t 00:10:00


module load bioinfo-tools
module load GATK/3.8-0


#Extracting Only Raw SNPs

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T SelectVariants \
    -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
    -V Controls_date_split.vcf \
    -selectType SNP \
    -o raw_SNPs_controls_date.vcf.gz


echo ExtractingSNPs done
