#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 1
#SBATCH -J RemoveSNPs
#SBATCH -t 00:30:00


module load bioinfo-tools
module load GATK/3.8-0


#Remove no call genotypes if not in 4 samples

java -jar $GATK_HOME/GenomeAnalysisTK.jar -T SelectVariants \
    -R /sw/data/uppnex/piper_references/2016-04-07/gatk_bundle/2.8/b37/human_g1k_v37.fasta \
    -V raw_SNPs_controls_date.vcf \
    -sn Control01 \
    -sn Control02 \
    -sn Control03 \
    --maxNOCALLnumber 4 \
    --excludeFiltered \
    -o Date_SNPs_controls_NoCallGenotypesRemoved.vcf


echo RemoveNoCallGenotypes done
