#! /bin/bash -l
#SBATCH -A project name
#SBATCH -p core
#SBATCH -n 1
#SBATCH -J VEP
#SBATCH -t 00:30:00


module load bioinfo-tools
module load GATK/3.8-0
module load vep/92


#Variant Effect Predictor (VEP)

vep \
--cache \
--dir $VEP_CACHE \
--refseq \
--offline \
--everything \
--assembly GRCh37 \
--use_given_ref \
--input_file HardFilteredSNPsRemoved_date.vcf \
--format vcf \
--vcf \
--output_file SNPs.VEP_date.vcf \


echo VEP done
